/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "FlowChat-Structs.h"
#import <Foundation/NSObject.h>

@class MVChatConnection, NSMutableDictionary, MVChatObject, NSString, NSMutableArray, ServerListController, ChatsListController, UITextField, NSThread;

__attribute__((visibility("hidden")))
@interface ChatCoreGUILink : NSObject {
	NSMutableDictionary* messageDictionary;
	NSMutableArray* activeConnections;
	NSString* inviteRoomName;
	NSString* inviteUserName;
	MVChatConnection* inviteConnection;
	MVChatConnection* errorTempConnection;
	NSString* errorTempRoom;
	UITextField* errorTempRoomField;
	ChatsListController* chatsController;
	ServerListController* serverController;
	MVChatObject* _currentChat;
	BOOL _isDisconnecting;
	BOOL _isKick;
	BOOL _isBan;
	NSThread* messageProcessingThread;
	NSMutableDictionary* needKeyDict;
	NSMutableArray* methods;
	NSMutableDictionary* _ezbFlagDict;
	NSMutableArray* _ezbSessions;
}
@property(retain) NSMutableDictionary* messageDictionary;
@property(retain) NSMutableDictionary* needKeyDict;
-(void)appWillQuit;
-(void)testMethod;
-(void)createMessageProcessingThread;
-(void)awakeFromNib;
-(void)timeStampsReset:(id)reset;
-(void)offscreenMessageAlert:(id)alert;
-(void)registerNotificationsForConnection:(id)connection;
-(void)unregisterNotificationsForConnection:(id)connection;
-(void)registerNotificationsForChatRoom:(id)chatRoom;
-(void)unregisterNotificationsForChatRoom:(id)chatRoom;
-(void)registerNotificationsForUser:(id)user;
-(void)unregisterNotificationsForUser:(id)user;
-(void)nickAccepted:(id)accepted;
-(void)updateNickname:(id)nickname;
-(void)userQuit:(id)quit;
-(void)userParted:(id)parted;
-(void)userJoined:(id)joined;
-(void)userKicked:(id)kicked;
-(void)gotRoomMessage:(id)message;
-(void)gotPrivMsg:(id)msg;
-(void)startPrivMsgWithUser:(id)user;
-(id)connectedServers;
-(void)willConnect:(id)connect;
-(void)didConnect:(id)connect;
-(void)refreshConnection:(id)connection;
-(void)didNotConnect:(id)connect;
-(void)didDisconnect:(id)disconnect;
-(void)channelJoined:(id)joined;
-(void)channelParted:(id)parted;
-(void)updateTopic:(id)topic;
-(void)handleRawIncomingMessage:(id)message InThread:(id)thread;
-(void)gotRawMsg:(id)msg;
-(void)showNeedKeyAlertForChan:(id)chan onNetwork:(id)network;
-(id)urlShorten:(id)shorten;
-(BOOL)message:(id)message isHighlightForString:(id)string;
-(id)getCurrentDate;
-(void)processMessageWithInfo:(id)info;
-(void)updateMessagesCount:(id)count reset:(BOOL)reset hasHighlight:(BOOL)highlight;
-(void)updateUsersForRoom:(id)room;
-(void)updateUserModes:(id)modes;
-(void)actOnInvite:(id)invite;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)kickedFromChannel:(id)channel;
-(void)bannedFromChannel:(id)channel;
-(void)gotWhois:(id)whois;
-(int)userStatusForUser:(id)user inRoom:(id)room;
-(void)loadLastMessagesForChat:(id)chat;
-(void)archiveChatLogForChat:(id)chat;
-(void)setCurrentChat:(id)chat;
-(id)currentChat;
-(void)clearDataForObject:(id)object;
-(void)gotPrefixTable:(id)table;
-(void)closePMWithUser:(id)user;
-(void)setChanTopic:(NSString*)topic;
@end

