/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSString, UIColor, NSNumber, TTStyledText;

__attribute__((visibility("hidden")))
@interface FCMessageString : NSObject <NSCoding> {
	NSString* senderNick;
	NSString* string;
	NSString* target;
	NSString* reason;
	NSString* readableString;
	NSString* XHTMLString;
	int messageType;
	UIColor* color;
	TTStyledText* styledText;
	NSString* date;
	NSNumber* hasHighlight;
	NSNumber* isMine;
	float width;
	float height;
	unsigned hashNum;
}
@property(retain) NSString* senderNick;
@property(retain) NSString* string;
@property(retain) NSString* target;
@property(retain) NSString* reason;
@property(retain) NSNumber* isMine;
@property(assign) int messageType;
@property(retain) NSNumber* hasHighlight;
@property(assign) float height;
@property(assign) float width;
@property(retain) TTStyledText* styledText;
@property(retain) NSString* date;
@property(copy) NSString* readableString;
@property(retain) UIColor* color;
@property(assign) unsigned hashNum;
@property(retain) NSString* XHTMLString;
-(void)processStringToStyledText;
-(void)beginThreadedProcessing;
-(void)doneProcessing:(id)processing;
-(id)initWithMessage:(id)message fromNick:(id)nick withTarget:(id)target withReason:(id)reason isMine:(id)mine highlight:(id)highlight atDate:(id)date withType:(int)type;
-(unsigned)hash;
-(void)genHash;
-(void)orientationChanged:(id)changed;
-(void)timeStampsEnabled:(id)enabled;
-(void)fontSizeChanged:(id)changed;
-(void)styleChanged:(id)changed;
-(void)showDate:(BOOL)date;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)description;
@end

