/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "UITabBarControllerDelegate.h"
//#import "UIApplicationDelegate.h"
//#import "UITextFieldDelegate.h"
#import <Foundation/Foundation.h>


@class ServerListController, RoarController, ChatsListController, PreferencesController, UIWindow, IgnoresController, UINavigationController, UIBarButtonItem, UITextField, UIView, UIImage, NSMutableDictionary, NSDictionary, MainTabBarController, ChatCoreGUILink, NSString, AliasesController;

__attribute__((visibility("hidden")))
@interface FlowChatAppDelegate : NSObject <UIApplicationDelegate, UITabBarControllerDelegate, UITextFieldDelegate> {
	UIWindow* window;
	MainTabBarController* tabBarController;
	ChatsListController* chatList;
	ChatCoreGUILink* guilink;
	UINavigationController* chatsNavigationController;
	PreferencesController* preferencesController;
	IgnoresController* ignoresController;
	ServerListController* serverListController;
	UIBarButtonItem* btn;
	UIBarButtonItem* donebtn;
	UITextField* nf;
	UITextField* uf;
	AliasesController* aliasesController;
	RoarController* roarController;
	UIView* welcome;
	UIImage* clock;
	UIImage* lines;
	UIImage* users;
	NSMutableDictionary* wantedDisconnect;
	NSMutableDictionary* wantedJoin;
	NSMutableDictionary* connAttempts;
	NSString* regUser;
	BOOL rotate;
	unsigned ref;
	int remoteHostStatus;
	int internetConnectionStatus;
	int localWiFiConnectionStatus;
	NSDictionary* serviceDict;
}
@property(retain) UIWindow* window;
@property(retain) MainTabBarController* tabBarController;
@property(assign) ChatsListController* chatList;
@property(retain) UINavigationController* chatsNavigationController;
@property(assign) ChatCoreGUILink* guilink;
@property(assign) PreferencesController* preferencesController;
@property(assign) IgnoresController* ignoresController;
@property(assign) ServerListController* serverListController;
@property(retain) NSMutableDictionary* wantedDisconnect;
@property(retain) NSMutableDictionary* wantedJoin;
@property(retain) NSMutableDictionary* connAttempts;
@property(assign) AliasesController* aliasesController;
@property(assign) RoarController* roarController;
@property(retain) UIImage* clock;
@property(retain) UIImage* lines;
@property(retain) UIImage* users;
@property(assign) BOOL rotate;
@property(assign) unsigned ref;
@property(assign) int remoteHostStatus;
@property(assign) int internetConnectionStatus;
@property(assign) int localWiFiConnectionStatus;
@property(retain) NSDictionary* serviceDict;
-(void)handleURL;
-(id)currentChatList;
-(id)init;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)updateStatus;
-(void)reachabilityChanged:(id)changed;
-(void)handleCrashReport;
-(id)getMainDictionary;
-(void)applicationDidFinishLaunching:(id)application;
-(void)createDefaultsWithNick:(id)nick andUser:(id)user;
-(void)save;
-(void)regWithUser:(id)user;
-(void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)deviceToken;
-(void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification;
-(void)applicationWillResignActive:(id)application;
-(BOOL)shouldRotate;
-(void)applicationWillTerminate:(id)application;
-(id)currentGUILink;
-(void)dealloc;
@end

