/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface MVChatObject : NSObject {
	BOOL isRoom;
	BOOL hasHighlight;
	int missedMessages;
	unsigned messageHash;
	unsigned loadIndex;
	NSArray* messageHistoryArray;
}
@property(assign) BOOL isRoom;
@property(assign) int missedMessages;
@property(assign) BOOL hasHighlight;
@property(assign) unsigned messageHash;
@property(assign) unsigned loadIndex;
@property(retain) NSArray* messageHistoryArray;
-(id)init;
-(id)oname;
-(void)sortMembers;
-(id)connection;
@end

