/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIDevice.h>


@interface UIDevice (Hardware)
-(id)getSysInfoByName:(char*)name;
-(id)platform;
-(unsigned)getSysInfo:(unsigned)info;
-(unsigned)cpuFrequency;
-(unsigned)busFrequency;
-(unsigned)totalMemory;
-(unsigned)userMemory;
-(unsigned)maxSocketBufferSize;
-(unsigned)platformType;
-(id)platformString;
-(unsigned)platformCapabilities;
-(id)macaddress;
@end

